# Generated by Django 3.0.8 on 2022-01-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220111_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
