# Generated by Django 3.0.8 on 2022-01-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220112_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='date_of_data',
        ),
    ]
