# Generated by Django 3.0.8 on 2022-01-12 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_data_date_of_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='date_of_data',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
