# Generated by Django 3.0.8 on 2022-01-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pearson_numbers_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pearson_numbers',
            new_name='corellation',
        ),
    ]
