# Generated by Django 3.0.8 on 2022-01-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_corellation_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='p_value',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='result',
            name='value',
            field=models.FloatField(default=1),
        ),
        migrations.DeleteModel(
            name='corellation',
        ),
    ]
