# Generated by Django 3.0.8 on 2022-01-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220114_2113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='result',
            new_name='result_cor',
        ),
    ]
